namespace Vidly.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulateMembershipTypes : DbMigration
    {
        public override void Up()
        {
            //IMPORTANT: In this migrations file, which was autogenerated from the PM shell 
            //(PM > add-migrations PopulateMembershiptypes), we're given a file where we can write code in order
            //to populate the database. Then after the code is written, we "update-database" at the PM prompt.
            Sql("INSERT INTO MembershipTypes (Id, SignupFee, DurationInMonths, DiscountRate) VALUES (1, 0, 0, 0)");
            Sql("INSERT INTO MembershipTypes (Id, SignupFee, DurationInMonths, DiscountRate) VALUES (2, 30, 1, 10)");
            Sql("INSERT INTO MembershipTypes (Id, SignupFee, DurationInMonths, DiscountRate) VALUES (3, 90, 3, 15)");
            Sql("INSERT INTO MembershipTypes (Id, SignupFee, DurationInMonths, DiscountRate) VALUES (4, 300, 12, 20)");
            
        }
        
        public override void Down()
        {
        }
    }
}
